create table recipe (
       id bigint generated by default as identity,
        ingredients varchar(100),
        instructions varchar(100),
        is_vegetarian boolean,
        last_updated timestamp,
        name varchar(50),
        serves integer check (serves<=8),
        primary key (id)
    )